function [opts]=setimportopts(task)

switch task
    case 'main'
        %% Set up the Import Options and import the data
        opts = delimitedTextImportOptions("NumVariables", 59, "Encoding", "UTF-8");

        % Specify range and delimiter
        opts.DataLines = [1, Inf];
        opts.Delimiter = ",";
        opts.VariableNamingRule='preserve';  %uses column headers as variable names
        % Specify column names and types
%         opts.VariableNames = ["Event Index", "UTC Timestamp",	"UTC Date",	"Local Timestamp", "Local Timezone","Local Date","Experiment ID",...
%             "Experiment Version", "Tree Node Key",	"Repeat Key",	"Schedule ID", "Participant Public ID",	"Participant Private ID",	"Participant Starting Group",...
%             "Participant Status",	"Participant Completion Code",	"Participant External Session ID",	"Participant Device Type",	"Participant Device",	"Participant OS",...
%             "Participant Browser",	"Participant Monitor Size",	"Participant Viewport Size", "Checkpoint",	"Task Name",	"Task Version",	"randomiser-6dgt",...
%             "Spreadsheet",	"Spreadsheet Name",	"Spreadsheet Row",	"Trial Number",	"Screen Number", "Screen Name",	"Zone Name",...
%             "Zone Type", "Reaction Time", "Reaction Onset",	"Response Type", "Response", "Attempt", "Correct", "Incorrect",	"Dishonest", "X Coordinate",...
%             "Y Coordinate",	"Timed Out", "randomise_blocks", "randomise_trials", "display",	"Cue",	"scale_left",	"scale_right",	"ITI",	"ANSWER",...
%             "scale_starting_point",	"Outcome"];

%         opts.VariableTypes = ["string", "string",	"string",	"string", "string","string","string",...
%             "string", "string",	"string",	"string", "string",	"double",	"string",...
%             "string",	"string",	"string",	"string",	"string",	"string",...
%             "string",	"string",	"string", "string",	"string",	"double",	"string",...
%             "string",	"string",	"double",	"double",	"double", "string",	"string",...
%             "string", "double", "string",	"string", "double", "double", "double", "double",	"double", "string",...
%             "string",	"double", "string", "string", "string",	"string",	"string",	"string",	"double",	"double",...
%             "double",	"string"];

        % adjusted excel columns for prolific!!!
          opts.VariableNames = ["Event Index", "UTC Timestamp",	"UTC Date",	"Local Timestamp", "Local Timezone","Local Date and Time","Experiment ID",...
            "Experiment Version", "Tree Node Key",	"Repeat Key",	"Schedule ID", "Participant Public ID",	"Participant Private ID",	"Participant Starting Group",...
            "Participant Status",	"Participant Completion Code",	"Participant External Session ID",	"Participant Device Type",	"Participant Device",	"Participant OS",...
            "Participant Browser",	"Participant Monitor Size",	"Participant Viewport Size", "Checkpoint",	"Room ID", "Room Order","Task Name",	"Task Version",	"randomiser-6dgt",...
            "Spreadsheet",	"Spreadsheet Name",	"Spreadsheet Row",	"Trial Number",	"Screen Number", "Screen Name",	"Zone Name",...
            "Zone Type", "Reaction Time", "Reaction Onset",	"Response Type", "Response", "Attempt", "Correct", "Incorrect",	"Dishonest", "X Coordinate",...
            "Y Coordinate",	"Timed Out", "randomise_blocks", "randomise_trials", "display",	"Cue",	"scale_left",	"scale_right",	"ITI",	"ANSWER",...
            "scale_starting_point",	"Outcome"];
        
        


        
        opts.VariableTypes = ["string", "string",	"string",	"string", "string","string","string",...
            "string", "string",	"string",	"string", "string",	"double",	"string",...
            "string",	"string",	"string",	"string",	"string",	"string",...
            "string",	"string",	"string", "string",	"string","string","string",	"double",	"string",...
            "string",	"string",	"double",	"double",	"double", "string",	"string",...
            "string", "double", "string",	"string", "double", "double", "double", "double",	"double", "string",...
            "string",	"double", "string", "string", "string",	"string",	"string",	"string",	"double",	"double",...
            "double",	"string"];

        opts.SelectedVariableNames = ["UTC Date","Participant Private ID","Spreadsheet Name","Zone Type","Reaction Time","Response","Timed Out","display","Cue","scale_left","scale_right","Outcome"];


        % Specify file level properties
        opts.ExtraColumnsRule = "ignore";
        opts.EmptyLineRule = "read";

        % Specify variable properties
        opts = setvaropts(opts, ["UTC Date","Participant Private ID","Spreadsheet Name","Zone Type","Reaction Time","Response","Timed Out","display","Cue","scale_left","scale_right","Outcome"], "EmptyFieldRule", "auto");


    case 'quest' %%%NOT CONFIGURED
        %% Set up the Import Options and import the data
        opts = delimitedTextImportOptions("NumVariables", 33, "Encoding", "UTF-8");

        % Specify range and delimiter
        opts.DataLines = [1, Inf];
        opts.Delimiter = ",";
        opts.VariableNamingRule='preserve';
        % Specify column names and types
        opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Participant Public ID", "Participant Private ID", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Question Key", "Response"];
        opts.SelectedVariableNames = ["Participant Public ID","Participant Private ID", "Question Key", "Response"];

        tmp=repmat("string",[1 33]);
        tmp(33)="double";
        tmp(13)="double";
        opts.VariableTypes = tmp;

        % Specify file level properties
        opts.ExtraColumnsRule = "ignore";
        opts.EmptyLineRule = "read";


        % Specify variable properties
        %  opts = setvaropts(opts, ["Participant Public ID","Participant Private ID", "Question Key", "Response"], "WhitespaceRule", "preserve");
        opts = setvaropts(opts, ["Participant Public ID","Participant Private ID", "Question Key", "Response"], "EmptyFieldRule", "auto");
end
end
